--- 

- hosts: aws 

#common options between modules 

  sudo: yes 

  gather_facts: no 

 

  vars_files: 

    - ./group_vars/vars.yml 

  roles: 

    - misc 

    - php 

    - mysql 

    - redis 

    - nginx 

    - bootstrap-app 

    - code-deploy 

    ### 

  handlers: 

    - include: handlers/main.yml
